### ISSUE TITLE
Parameter remote control

### ISSUE THREAD

**Issue by pingdynasty** [RebelTechnology/OwlServer#260]
Parameter remote control (send MIDI from knobs).

The user should be able to 'remote control' a connected OWL using the virtual knobs on the Patch Details page.

Depends on #258 (goes into Device tab)

**Comment by f-rebeltech** [comment]
[c759f10](https://github.com/RebelTechnology/OwlServer/commit/c759f108cb22132e3c2215def7a8fcfd25f0e38a)
